### ISSUE TITLE
Request for org name

### ISSUE THREAD

**Issue by davedbase** [jbytescript/bytescript#1]
Hello @csadilek! I'm writing on behalf of a small group that's working to to initiate a new project that we're hoping to call ByteScript. We're working on a new TypeScript to WASM compiler and would love to adopt the name. It does seem like this org/repo is currently being under-utilized. I was wondering if you might be gracious enough to allow us the privilege of leveraging it.

Thank you for your consideration. You can reach me on twitter @davedbase directly.

David

**Comment by csadilek** [comment]
This is for @jfuerth to decide, who came up with the idea, initiative, and did all the groundwork. I never got around to work on this.

Also, hi :).

**Comment by jfuerth** [comment]
Hi @davedbase and thanks for the ping, @csadilek!

I'm happy to give this org name to a new home. What's the best way to transfer it to you?

**Comment by davedbase** [comment]
@jfuerth that's so kind of you, thank you so much! I believe the process is to add me to the org with all the admin permissions.

**Comment by trusktr** [comment]
Hello @jfuerth, thanks for this! Here with @davedbase. We can rename the current bytescript org to anything, then we can rename the other org we have.

**Comment by jfuerth** [comment]
@davedbase @trusktr So sorry for the delay! I've invited you both as org members. Proceed with the rename when you wish! You can call this org `jbytescript` if that's available.

**Comment by davedbase** [comment]
Thanks so much @jfuerth! The rename is complete. I was wondering if you happened to own the npm organization as well? Trying to figure out who snagged it.

**Comment by jfuerth** [comment]
Sorry @davedbase, I don't know about the npm org. Must be a different project.

Best of luck with bytescript!
